# EUREKA
version: '3.8'
services:
  registry-discovery:
    container_name: id-eureka
    image: paymentchain/microservice-docker-eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xmx256M
# CONFIGURATION
  configuration:
    container_name: id-config
    image: paymentchain/microservice-docker-config-server:0.0.1-SNAPSHOT
    volumes:
      - ./config-server-repo:/tmp/config-server-repo
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -DLOCAL_REPOSITORY=/tmp/config-server-repo
    depends_on:
      - registry-discovery
    ports:
      - "8888:8888"
# ADMINISTRATION
  administration:
    container_name: id-admin
    image: paymentchain/microservice-docker-admin-server:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - "8762:8762"

  api-gateway:
    container_name: id-apigateway
    image: paymentchain/microservice-docker-api-gateway:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - "8080:8080"

  keycloack:
    container_name: keycloack-adapter
    image: paymentchain/microservice-docker-keycloack-adapter:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xms256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -DKEYCLOACK_SERVER=http://keycloack_server:8080/auth/realms/
         -DKEYCLOACK_REAL_ID=G3tJYnggYU6LUzf-CIjSlN6BQSm2Ii12Vq1ThgcmhF8
    depends_on:
      - registry-discovery
    ports:
      - "8088:8088"

      # PRODUCT
  product-catalog:
    container_name: bd-product-catalog
    image: paymentchain/microservice-docker-product:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8083:8083"
# CUSTOMER
  customer:
    container_name: bd-customer
    image: paymentchain/microservice-docker-customer:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
# Transaction
  transactions:
    container_name: bd-transactions
    image: paymentchain/microservice-docker-transaction:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
         -Xms256M
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - "8082:8082"
# DATABASE SERVICE
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "3432:5432"
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
#PGADMIN SERVICE
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "80:80"
    depends_on:
      - postgres_db
# Keycloack Server
  keycloack_server:
    container_name: id-keycloackServer
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - "8091:8080"